<!DOCTYPE html>
<html lang="id">
<head>
<meta charset="utf-8">
<title>Proposal {{ $proposal->number }}</title>
<style>
  @page { margin: 32px 36px; }
  body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1e293b; line-height: 1.5; }
  h1 { font-size: 28px; margin: 0; color: #4f46e5; letter-spacing: -.02em; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 28px; padding-bottom: 18px; border-bottom: 1px solid #e5e7eb; }
  .brand { font-size: 13px; font-weight: 700; color: #4f46e5; }
  .meta { text-align: right; font-size: 11px; color: #475569; }
  .subject { font-size: 22px; font-weight: 700; margin: 16px 0 12px; color: #0f172a; }
  .recipient { background: #f8fafc; padding: 14px; border-radius: 8px; margin-bottom: 18px; font-size: 11px; }
  .body { line-height: 1.7; }
  .value-box { background: #eef2ff; border-radius: 10px; padding: 18px; margin-top: 24px; text-align: center; }
  .value-box .label { font-size: 11px; color: #6366f1; text-transform: uppercase; letter-spacing: .08em; font-weight: 700; }
  .value-box .amount { font-size: 26px; font-weight: 800; color: #4f46e5; margin-top: 4px; }
  .sig-block { margin-top: 32px; padding-top: 20px; border-top: 1px solid #e5e7eb; }
  .sig-block .sig-by { font-size: 13px; font-weight: 700; }
  .sig-block .sig-meta { font-size: 10px; color: #94a3b8; margin-top: 4px; }
  .footer { margin-top: 36px; font-size: 10px; color: #94a3b8; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 12px; }
</style>
</head>
<body>
<div class="header">
  <div>
    <h1>PROPOSAL</h1>
    <div class="brand">{{ $appName }}</div>
  </div>
  <div class="meta">
    <div><strong>Number:</strong> {{ $proposal->number }}</div>
    @if($proposal->open_until)<div><strong>Valid until:</strong> {{ $proposal->open_until->format('d M Y') }}</div>@endif
  </div>
</div>

<div class="subject">{{ $proposal->subject }}</div>

<div class="recipient">
  <strong>Prepared for:</strong> {{ $proposal->client?->company_name ?? $proposal->lead?->name }}
</div>

<div class="body">{!! $proposal->content !!}</div>

<div class="value-box">
  <div class="label">Proposal Value</div>
  <div class="amount">{{ $proposal->currency->symbol ?? 'Rp' }} {{ number_format($proposal->total, 0, ',', '.') }}</div>
</div>

@if($proposal->signed_at ?? $proposal->accepted_at)
  <div class="sig-block">
    <div class="sig-by">✓ Accepted by {{ $proposal->accepted_by_name }}</div>
    <div class="sig-meta">{{ $proposal->accepted_at?->format('d M Y H:i') }} · IP {{ $proposal->accepted_ip }}</div>
  </div>
@endif

<div class="footer">Generated by {{ $appName }} · {{ now()->format('d M Y H:i') }}</div>
</body>
</html>
