<?php

return [
    'industries' => [
        // --- Professional Services ---
        'agencies' => ['display' => 'Agencies', 'tagline' => 'Manage clients, projects, billing & support'],
        'freelancers' => ['display' => 'Freelancers', 'tagline' => 'Pro invoicing, proposals, contracts'],
        'real-estate' => ['display' => 'Real Estate', 'tagline' => 'Lead pipeline, listings, deal closing'],
        'msps' => ['display' => 'MSPs', 'tagline' => 'Ticketing + recurring billing for IT services'],
        'consultants' => ['display' => 'Consultants', 'tagline' => 'Engagement tracking + retainer billing'],
        'law-firms' => ['display' => 'Law Firms', 'tagline' => 'Matter management + billable hours'],
        'accountants' => ['display' => 'Accountants', 'tagline' => 'Recurring services + multi-client portal'],
        'marketing-agencies' => ['display' => 'Marketing Agencies', 'tagline' => 'Campaign tracking + retainer'],
        'design-studios' => ['display' => 'Design Studios', 'tagline' => 'Creative projects + asset delivery'],
        'it-services' => ['display' => 'IT Services', 'tagline' => 'Tickets, projects, recurring contracts'],
        'architects' => ['display' => 'Architects', 'tagline' => 'Project phasing, billable hours, deliverables'],
        'engineers' => ['display' => 'Engineering Firms', 'tagline' => 'Phase billing, milestone payments'],
        'event-planners' => ['display' => 'Event Planners', 'tagline' => 'Vendor mgmt, deposits, run-of-show'],
        'translators' => ['display' => 'Translators', 'tagline' => 'Word-count quotes, multi-currency invoicing'],
        'contractors' => ['display' => 'General Contractors', 'tagline' => 'Estimates, change orders, draws'],
        'photographers' => ['display' => 'Photographers', 'tagline' => 'Client portal + gallery delivery'],
        'tutors' => ['display' => 'Tutors & Coaches', 'tagline' => 'Sessions, packages, recurring billing'],
        'dental-clinics' => ['display' => 'Dental Clinics', 'tagline' => 'Appointment scheduling + treatment plans'],
        'veterinary' => ['display' => 'Veterinary Clinics', 'tagline' => 'Pet patient records + appointment booking'],
        'wedding-planners' => ['display' => 'Wedding Planners', 'tagline' => 'Vendor coordination + payment schedules'],
        'interior-designers' => ['display' => 'Interior Designers', 'tagline' => 'Project moodboards + procurement tracking'],
        'web-developers' => ['display' => 'Web Developers', 'tagline' => 'Retainer clients + milestone billing'],
        'digital-agencies' => ['display' => 'Digital Agencies', 'tagline' => 'Multi-client campaign + retainer management'],
        'seo-agencies' => ['display' => 'SEO Agencies', 'tagline' => 'Monthly reporting + rank tracking'],
        'content-creators' => ['display' => 'Content Creators', 'tagline' => 'Sponsorship deals + content calendar'],
        'video-producers' => ['display' => 'Video Producers', 'tagline' => 'Production phases + revision cycles'],
        'podcasters' => ['display' => 'Podcasters', 'tagline' => 'Sponsor deals + episode scheduling'],
        'music-teachers' => ['display' => 'Music Teachers', 'tagline' => 'Lesson scheduling + recital planning'],
        'driving-schools' => ['display' => 'Driving Schools', 'tagline' => 'Student progress + test scheduling'],
        'language-schools' => ['display' => 'Language Schools', 'tagline' => 'Course enrollment + level tracking'],
        'fitness-trainers' => ['display' => 'Fitness Trainers', 'tagline' => 'Client programs + session packages'],
        'yoga-studios' => ['display' => 'Yoga Studios', 'tagline' => 'Class scheduling + membership billing'],
        'pilates-studios' => ['display' => 'Pilates Studios', 'tagline' => 'Reformer sessions + package management'],
        'physiotherapists' => ['display' => 'Physiotherapists', 'tagline' => 'Treatment plans + insurance claims'],
        'chiropractors' => ['display' => 'Chiropractors', 'tagline' => 'Adjustment tracking + wellness plans'],
        'dentists' => ['display' => 'Dentists', 'tagline' => 'Patient records + treatment estimates'],
        'optometrists' => ['display' => 'Optometrists', 'tagline' => 'Eye exam scheduling + prescription records'],
        'pharmacies' => ['display' => 'Pharmacies', 'tagline' => 'Inventory + prescription management'],
        'home-care' => ['display' => 'Home Care Services', 'tagline' => 'Caregiver scheduling + visit logs'],
        'cleaning-services' => ['display' => 'Cleaning Services', 'tagline' => 'Recurring cleanings + crew dispatch'],
        'pest-control' => ['display' => 'Pest Control', 'tagline' => 'Route scheduling + treatment history'],
        'landscaping' => ['display' => 'Landscaping', 'tagline' => 'Seasonal contracts + crew management'],
        'pool-service' => ['display' => 'Pool Service', 'tagline' => 'Weekly maintenance + chemical logs'],
        'hvac-services' => ['display' => 'HVAC Services', 'tagline' => 'Service calls + maintenance contracts'],
        'plumbing' => ['display' => 'Plumbing', 'tagline' => 'Emergency dispatch + estimate pipeline'],
        'electrical' => ['display' => 'Electrical Contractors', 'tagline' => 'Permit tracking + inspection scheduling'],
        'roofing' => ['display' => 'Roofing', 'tagline' => 'Inspection → estimate → project completion'],
        'painting' => ['display' => 'Painting Contractors', 'tagline' => 'Room-by-room estimates + color tracking'],
        'moving-companies' => ['display' => 'Moving Companies', 'tagline' => 'Inventory lists + route planning'],
        'storage-facilities' => ['display' => 'Storage Facilities', 'tagline' => 'Unit rentals + access logs'],
        'carpet-cleaning' => ['display' => 'Carpet Cleaning', 'tagline' => 'Appointment booking + before/after photos'],
        'window-cleaning' => ['display' => 'Window Cleaning', 'tagline' => 'Route optimization + recurring contracts'],
        'solar-installers' => ['display' => 'Solar Installers', 'tagline' => 'Site surveys + permit tracking'],
        'security-companies' => ['display' => 'Security Companies', 'tagline' => 'Guard scheduling + incident reports'],
        'private-investigators' => ['display' => 'Private Investigators', 'tagline' => 'Case management + evidence tracking'],
        'locksmiths' => ['display' => 'Locksmiths', 'tagline' => 'Emergency dispatch + key management'],
        'notaries' => ['display' => 'Notaries', 'tagline' => 'Document prep + appointment scheduling'],
        'tax-preparers' => ['display' => 'Tax Preparers', 'tagline' => 'Client documents + filing deadlines'],
        'bookkeepers' => ['display' => 'Bookkeepers', 'tagline' => 'Monthly close + reconciliation'],
        'payroll-services' => ['display' => 'Payroll Services', 'tagline' => 'Multi-client payroll + tax filings'],
        'hr-consultants' => ['display' => 'HR Consultants', 'tagline' => 'Engagement letters + retainer billing'],
        'recruiters' => ['display' => 'Recruiters', 'tagline' => 'Candidate pipeline + placement tracking'],
        'staffing-agencies' => ['display' => 'Staffing Agencies', 'tagline' => 'Temp placement + timesheet management'],
        'virtual-assistants' => ['display' => 'Virtual Assistants', 'tagline' => 'Multi-client task management + time tracking'],
        'call-centers' => ['display' => 'Call Centers', 'tagline' => 'Agent scheduling + call logs'],
        'telemarketing' => ['display' => 'Telemarketing', 'tagline' => 'Call lists + conversion tracking'],
        'market-research' => ['display' => 'Market Research', 'tagline' => 'Survey deployment + respondent management'],
        'pr-agencies' => ['display' => 'PR Agencies', 'tagline' => 'Media contacts + press release tracking'],
        'branding-agencies' => ['display' => 'Branding Agencies', 'tagline' => 'Brand guidelines + asset library'],
        'social-media-managers' => ['display' => 'Social Media Managers', 'tagline' => 'Content calendar + analytics reporting'],
        'influencers' => ['display' => 'Influencers', 'tagline' => 'Sponsorship pipeline + content schedule'],
        'affiliate-marketers' => ['display' => 'Affiliate Marketers', 'tagline' => 'Campaign tracking + commission payouts'],
        // --- E-Commerce & Digital Products ---
        'ecommerce-stores' => ['display' => 'E-Commerce Stores', 'tagline' => 'Order management + customer profiles'],
        'dropshippers' => ['display' => 'Dropshippers', 'tagline' => 'Supplier management + order routing'],
        'amazon-sellers' => ['display' => 'Amazon Sellers', 'tagline' => 'Inventory sync + PPC tracking'],
        'etsy-sellers' => ['display' => 'Etsy Sellers', 'tagline' => 'Custom orders + production tracking'],
        'shopify-stores' => ['display' => 'Shopify Stores', 'tagline' => 'Multi-channel order + customer management'],
        'saas-companies' => ['display' => 'SaaS Companies', 'tagline' => 'MRR tracking + churn reduction pipeline'],
        'mobile-app-developers' => ['display' => 'Mobile App Developers', 'tagline' => 'Dev projects + App Store release tracking'],
        'game-developers' => ['display' => 'Game Developers', 'tagline' => 'Asset pipeline + build release tracking'],
        'blockchain-developers' => ['display' => 'Blockchain Developers', 'tagline' => 'Smart contract audits + dApp deployment'],
        // --- Tech Startups ---
        'ai-startups' => ['display' => 'AI Startups', 'tagline' => 'Model training pipeline + API customer billing'],
        'fintech' => ['display' => 'Fintech', 'tagline' => 'Regulatory compliance + transaction monitoring'],
        'insurtech' => ['display' => 'Insurtech', 'tagline' => 'Policy management + claims pipeline'],
        'healthtech' => ['display' => 'Healthtech', 'tagline' => 'Patient data + HIPAA-compliant tracking'],
        'edtech' => ['display' => 'Edtech', 'tagline' => 'Student enrollment + course progress'],
        'proptech' => ['display' => 'Proptech', 'tagline' => 'Property listings + tenant management'],
        'legaltech' => ['display' => 'Legaltech', 'tagline' => 'Case management + document automation'],
        'agritech' => ['display' => 'Agritech', 'tagline' => 'Farm management + harvest tracking'],
        // --- Logistics & Trade ---
        'logistics' => ['display' => 'Logistics', 'tagline' => 'Shipment tracking + proof of delivery'],
        'courier-services' => ['display' => 'Courier Services', 'tagline' => 'Pickup-dispatch-delivery pipeline'],
        'freight-forwarders' => ['display' => 'Freight Forwarders', 'tagline' => 'Cargo booking + customs clearance'],
        'import-export' => ['display' => 'Import Export', 'tagline' => 'Trade docs + LC management'],
        'wholesalers' => ['display' => 'Wholesalers', 'tagline' => 'Bulk order + tier pricing management'],
        'distributors' => ['display' => 'Distributors', 'tagline' => 'Multi-channel distribution + inventory'],
        'manufacturers' => ['display' => 'Manufacturers', 'tagline' => 'Production orders + BOM tracking'],
        // --- Manufacturing & Custom ---
        'print-shops' => ['display' => 'Print Shops', 'tagline' => 'Print job queue + proof approval'],
        'sign-makers' => ['display' => 'Sign Makers', 'tagline' => 'Custom sign design + permit tracking'],
        'embroidery-shops' => ['display' => 'Embroidery Shops', 'tagline' => 'Digitizing + production queue'],
        'screen-printers' => ['display' => 'Screen Printers', 'tagline' => 'Screen prep + color separation tracking'],
        // --- Food & Beverage ---
        'bakeries' => ['display' => 'Bakeries', 'tagline' => 'Custom cake orders + production schedule'],
        'caterers' => ['display' => 'Caterers', 'tagline' => 'Event catering + menu planning'],
        'food-trucks' => ['display' => 'Food Trucks', 'tagline' => 'Location schedule + inventory management'],
        'coffee-shops' => ['display' => 'Coffee Shops', 'tagline' => 'Wholesale orders + bean inventory'],
        'restaurants' => ['display' => 'Restaurants', 'tagline' => 'Event bookings + supplier management'],
        'bars' => ['display' => 'Bars', 'tagline' => 'Event reservations + inventory control'],
        'nightclubs' => ['display' => 'Nightclubs', 'tagline' => 'VIP table booking + promoter tracking'],
        // --- Venue & Hospitality ---
        'event-venues' => ['display' => 'Event Venues', 'tagline' => 'Booking calendar + vendor coordination'],
        'coworking-spaces' => ['display' => 'Coworking Spaces', 'tagline' => 'Membership + room booking management'],
        'coliving-spaces' => ['display' => 'Coliving Spaces', 'tagline' => 'Tenant onboarding + amenity booking'],
        'property-managers' => ['display' => 'Property Managers', 'tagline' => 'Maintenance requests + rent collection'],
        'airbnb-hosts' => ['display' => 'Airbnb Hosts', 'tagline' => 'Guest communication + turnover scheduling'],
        // --- Travel & Leisure ---
        'travel-agencies' => ['display' => 'Travel Agencies', 'tagline' => 'Itinerary building + supplier contracts'],
        'tour-operators' => ['display' => 'Tour Operators', 'tagline' => 'Group bookings + guide scheduling'],
        'dive-centers' => ['display' => 'Dive Centers', 'tagline' => 'Course scheduling + equipment rental'],
        'surf-schools' => ['display' => 'Surf Schools', 'tagline' => 'Lesson packages + board rental'],
        'ski-resorts' => ['display' => 'Ski Resorts', 'tagline' => 'Lift pass + lesson booking'],
        'golf-clubs' => ['display' => 'Golf Clubs', 'tagline' => 'Tee time + membership management'],
        'tennis-clubs' => ['display' => 'Tennis Clubs', 'tagline' => 'Court booking + coaching programs'],
        'martial-arts' => ['display' => 'Martial Arts', 'tagline' => 'Belt progression + tournament tracking'],
        'dance-studios' => ['display' => 'Dance Studios', 'tagline' => 'Class schedule + recital planning'],
        'startups' => ['display' => 'Startups', 'tagline' => 'Lead-to-cash pipeline from day one'],
    ],

    'cities' => [
        // --- Indonesia ---
        'jakarta' => 'Jakarta',
        'jakarta-pusat' => 'Jakarta Pusat',
        'jakarta-barat' => 'Jakarta Barat',
        'jakarta-selatan' => 'Jakarta Selatan',
        'jakarta-timur' => 'Jakarta Timur',
        'jakarta-utara' => 'Jakarta Utara',
        'tangerang' => 'Tangerang',
        'tangerang-selatan' => 'Tangerang Selatan',
        'bekasi' => 'Bekasi',
        'depok' => 'Depok',
        'bogor' => 'Bogor',
        'cibinong' => 'Cibinong',
        'cikarang' => 'Cikarang',
        'karawang' => 'Karawang',
        'purwakarta' => 'Purwakarta',
        'subang' => 'Subang',
        'sumedang' => 'Sumedang',
        'cimahi' => 'Cimahi',
        'bandung' => 'Bandung',
        'cirebon' => 'Cirebon',
        'tasikmalaya' => 'Tasikmalaya',
        'garut' => 'Garut',
        'cianjur' => 'Cianjur',
        'sukabumi' => 'Sukabumi',
        'semarang' => 'Semarang',
        'solo' => 'Solo',
        'surakarta' => 'Surakarta',
        'yogyakarta' => 'Yogyakarta',
        'magelang' => 'Magelang',
        'salatiga' => 'Salatiga',
        'pekalongan' => 'Pekalongan',
        'tegal' => 'Tegal',
        'purwokerto' => 'Purwokerto',
        'cilacap' => 'Cilacap',
        'kebumen' => 'Kebumen',
        'surabaya' => 'Surabaya',
        'madiun' => 'Madiun',
        'kediri' => 'Kediri',
        'malang' => 'Malang',
        'batu' => 'Batu',
        'blitar' => 'Blitar',
        'tulungagung' => 'Tulungagung',
        'probolinggo' => 'Probolinggo',
        'jember' => 'Jember',
        'banyuwangi' => 'Banyuwangi',
        'sidoarjo' => 'Sidoarjo',
        'gresik' => 'Gresik',
        'mojokerto' => 'Mojokerto',
        'pasuruan' => 'Pasuruan',
        'lamongan' => 'Lamongan',
        'tuban' => 'Tuban',
        'bojonegoro' => 'Bojonegoro',
        'ngawi' => 'Ngawi',
        'ponorogo' => 'Ponorogo',
        'pacitan' => 'Pacitan',
        'trenggalek' => 'Trenggalek',
        'lumajang' => 'Lumajang',
        'bondowoso' => 'Bondowoso',
        'situbondo' => 'Situbondo',
        'sumenep' => 'Sumenep',
        'pamekasan' => 'Pamekasan',
        'sampang' => 'Sampang',
        'bangkalan' => 'Bangkalan',
        'denpasar' => 'Denpasar',
        'badung' => 'Badung',
        'gianyar' => 'Gianyar',
        'tabanan' => 'Tabanan',
        'singaraja' => 'Singaraja',
        'mataram' => 'Mataram',
        'praya' => 'Praya',
        'sumbawa' => 'Sumbawa',
        'bima' => 'Bima',
        'kupang' => 'Kupang',
        'ende' => 'Ende',
        'maumere' => 'Maumere',
        'medan' => 'Medan',
        'binjai' => 'Binjai',
        'pematangsiantar' => 'Pematangsiantar',
        'tebing-tinggi' => 'Tebing Tinggi',
        'padang-sidempuan' => 'Padang Sidempuan',
        'sibolga' => 'Sibolga',
        'tanjung-balai' => 'Tanjung Balai',
        'kisaran' => 'Kisaran',
        'rantau-prapat' => 'Rantau Prapat',
        'pekanbaru' => 'Pekanbaru',
        'dumai' => 'Dumai',
        'batam' => 'Batam',
        'tanjung-pinang' => 'Tanjung Pinang',
        'pangkal-pinang' => 'Pangkal Pinang',
        'jambi' => 'Jambi',
        'palembang' => 'Palembang',
        'lubuklinggau' => 'Lubuklinggau',
        'prabumulih' => 'Prabumulih',
        'bengkulu' => 'Bengkulu',
        'bandar-lampung' => 'Bandar Lampung',
        'metro' => 'Metro',
        'pontianak' => 'Pontianak',
        'singkawang' => 'Singkawang',
        'ketapang' => 'Ketapang',
        'sintang' => 'Sintang',
        'palangkaraya' => 'Palangkaraya',
        'sampit' => 'Sampit',
        'banjarmasin' => 'Banjarmasin',
        'banjarbaru' => 'Banjarbaru',
        'martapura' => 'Martapura',
        'balikpapan' => 'Balikpapan',
        'samarinda' => 'Samarinda',
        'bontang' => 'Bontang',
        'tarakan' => 'Tarakan',
        'nunukan' => 'Nunukan',
        'manado' => 'Manado',
        'bitung' => 'Bitung',
        'tomohon' => 'Tomohon',
        'gorontalo' => 'Gorontalo',
        'palu' => 'Palu',
        'poso' => 'Poso',
        'luwuk' => 'Luwuk',
        'kendari' => 'Kendari',
        'bau-bau' => 'Bau-Bau',
        'makassar' => 'Makassar',
        'parepare' => 'Parepare',
        'palopo' => 'Palopo',
        'watampone' => 'Watampone',
        'bulukumba' => 'Bulukumba',
        'jeneponto' => 'Jeneponto',
        'bantaeng' => 'Bantaeng',
        'mamuju' => 'Mamuju',
        'majene' => 'Majene',
        'ambon' => 'Ambon',
        'tual' => 'Tual',
        'ternate' => 'Ternate',
        'tidore' => 'Tidore',
        'sofifi' => 'Sofifi',
        'manokwari' => 'Manokwari',
        'sorong' => 'Sorong',
        'jayapura' => 'Jayapura',
        'merauke' => 'Merauke',
        'timika' => 'Timika',
        'wamena' => 'Wamena',
        'nabire' => 'Nabire',
        'biak' => 'Biak',
        'serui' => 'Serui',
        // --- ASEAN ---
        'singapore' => 'Singapore',
        'orchard' => 'Orchard',
        'marina-bay' => 'Marina Bay',
        'tampines' => 'Tampines',
        'jurong-east' => 'Jurong East',
        'woodlands' => 'Woodlands',
        'kuala-lumpur' => 'Kuala Lumpur',
        'klcc' => 'KLCC',
        'bangsar' => 'Bangsar',
        'damansara' => 'Damansara',
        'cheras' => 'Cheras',
        'penang' => 'Penang',
        'johor-bahru' => 'Johor Bahru',
        'kota-kinabalu' => 'Kota Kinabalu',
        'kuching' => 'Kuching',
        'manila' => 'Manila',
        'quezon-city' => 'Quezon City',
        'makati' => 'Makati',
        'cebu' => 'Cebu',
        'davao' => 'Davao',
        'bangkok' => 'Bangkok',
        'chiang-mai' => 'Chiang Mai',
        'pattaya' => 'Pattaya',
        'phuket' => 'Phuket',
        'hanoi' => 'Hanoi',
        'ho-chi-minh-city' => 'Ho Chi Minh City',
        'da-nang' => 'Da Nang',
        'nha-trang' => 'Nha Trang',
        'yangon' => 'Yangon',
        'mandalay' => 'Mandalay',
        'phnom-penh' => 'Phnom Penh',
        'siem-reap' => 'Siem Reap',
        'vientiane' => 'Vientiane',
        'luang-prabang' => 'Luang Prabang',
        'bandar-seri-begawan' => 'Bandar Seri Begawan',
        'dili' => 'Dili',
    ],

    'roles' => [
        'sales' => 'Sales Team',
        'marketing' => 'Marketing Team',
        'support' => 'Support Team',
        'finance' => 'Finance Team',
        'project-managers' => 'Project Managers',
        'owners' => 'Business Owners',
        'agencies' => 'Agency Owners',
        'freelancers' => 'Freelancers',
        'consultants' => 'Consultants',
        'accountants' => 'Accountants',
        'lawyers' => 'Lawyers',
        'architects' => 'Architects',
        'engineers' => 'Engineers',
        'photographers' => 'Photographers',
        'videographers' => 'Videographers',
        'designers' => 'Designers',
        'developers' => 'Developers',
        'writers' => 'Writers',
        'translators' => 'Translators',
        'virtual-assistants' => 'Virtual Assistants',
        'coaches' => 'Coaches',
        'trainers' => 'Trainers',
        'therapists' => 'Therapists',
        'doctors' => 'Doctors',
        'dentists' => 'Dentists',
        'veterinarians' => 'Veterinarians',
        'real-estate-agents' => 'Real Estate Agents',
        'insurance-agents' => 'Insurance Agents',
        'travel-agents' => 'Travel Agents',
        'event-planners' => 'Event Planners',
        'wedding-planners' => 'Wedding Planners',
        'property-managers' => 'Property Managers',
        'restaurant-owners' => 'Restaurant Owners',
        'retail-owners' => 'Retail Owners',
        'ecommerce-owners' => 'Ecommerce Owners',
        'startup-founders' => 'Startup Founders',
        'hr-managers' => 'HR Managers',
        'operations-managers' => 'Operations Managers',
        'customer-success' => 'Customer Success',
        'account-managers' => 'Account Managers',
        'business-development' => 'Business Development',
    ],

    'pricing-bands' => [
        '50' => 50,
        '100' => 100,
        '250' => 250,
        '500' => 500,
        '1000' => 1000,
        '2500' => 2500,
        '5000' => 5000,
        '10000' => 10000,
    ],

    'competitors' => [
        'perfex' => [
            'display' => 'Perfex CRM',
            'tagline' => 'CodeIgniter-based, CodeCanyon license',
            'pros' => ['Cheap one-time license', 'Wide feature set', 'Active marketplace'],
            'cons' => ['Legacy stack (CI3 + jQuery)', 'Obfuscated source (ionCube)', 'Hardcoded gateways', 'Outdated UX'],
        ],
        'hubspot' => [
            'display' => 'HubSpot CRM',
            'tagline' => 'Marketing-led growth platform',
            'pros' => ['Polished marketing automation', 'Strong free tier'],
            'cons' => ['Expensive paid tiers', 'SaaS lock-in', 'No self-host'],
        ],
        'zoho-crm' => [
            'display' => 'Zoho CRM',
            'tagline' => 'Suite-style CRM with deep customization',
            'pros' => ['Extensive integrations', 'Tiered pricing'],
            'cons' => ['UI clutter', 'Steep learning curve', 'SaaS only'],
        ],
        'freshsales' => [
            'display' => 'Freshsales',
            'tagline' => 'Sales-focused CRM by Freshworks',
            'pros' => ['Clean UI', 'AI lead scoring'],
            'cons' => ['Limited project management', 'SaaS only'],
        ],
        'pipedrive' => [
            'display' => 'Pipedrive',
            'tagline' => 'Pipeline-first CRM',
            'pros' => ['Best-in-class pipeline UX', 'Simple onboarding'],
            'cons' => ['No invoicing native', 'No support tickets', 'SaaS only'],
        ],
        'monday-com' => [
            'display' => 'Monday.com',
            'tagline' => 'Work OS with CRM add-on',
            'pros' => ['Flexible boards', 'Strong PM features'],
            'cons' => ['CRM is bolt-on', 'Pricey at scale'],
        ],
        'bonsai' => [
            'display' => 'Bonsai',
            'tagline' => 'Freelancer ops platform',
            'pros' => ['All-in-one for solopreneurs', 'Modern UX'],
            'cons' => ['Limited team features', 'USD pricing', 'No self-host'],
        ],
        'honeybook' => [
            'display' => 'HoneyBook',
            'tagline' => 'Service business CRM (US-focused)',
            'pros' => ['Beautiful templates', 'Good for events/photographers'],
            'cons' => ['US-only payments', 'No multi-currency natively'],
        ],
        'bitrix24' => [
            'display' => 'Bitrix24',
            'tagline' => 'All-in-one suite',
            'pros' => ['Free tier generous', 'Self-host available'],
            'cons' => ['Overwhelming UI', 'Performance issues'],
        ],
        'espocrm' => [
            'display' => 'EspoCRM',
            'tagline' => 'Open-source CRM',
            'pros' => ['Free open-source core', 'Self-hostable'],
            'cons' => ['Smaller community', 'Limited billing features'],
        ],
        'salesforce' => [
            'display' => 'Salesforce',
            'tagline' => 'Enterprise CRM market leader',
            'pros' => ['Most extensible', 'Massive ecosystem'],
            'cons' => ['Expensive per seat', 'Implementation overhead', 'SaaS only'],
        ],
        'odoo' => [
            'display' => 'Odoo CRM',
            'tagline' => 'ERP suite with CRM module',
            'pros' => ['Tightly integrated suite', 'Self-host edition'],
            'cons' => ['Best value when using full ERP', 'Steep learning curve'],
        ],
    ],

    'countries' => [
        'indonesia' => [
            'display' => 'Indonesia', 'currency' => 'IDR', 'tax' => 'PPN 11%', 'language' => 'id',
            'local_gateways' => ['Midtrans', 'Xendit', 'DOKU', 'Faspay', 'QRIS'],
            'compliance' => ['e-Faktur', 'UU PDP 2022'],
        ],
        'singapore' => [
            'display' => 'Singapore', 'currency' => 'SGD', 'tax' => 'GST 9%', 'language' => 'en',
            'local_gateways' => ['Stripe SG', 'NETS', 'PayNow', 'eNETS'], 'compliance' => ['PDPA'],
        ],
        'malaysia' => [
            'display' => 'Malaysia', 'currency' => 'MYR', 'tax' => 'SST 6%', 'language' => 'en',
            'local_gateways' => ['iPay88', 'Billplz', 'eGHL', 'DuitNow'], 'compliance' => ['PDPA Malaysia'],
        ],
        'philippines' => [
            'display' => 'Philippines', 'currency' => 'PHP', 'tax' => 'VAT 12%', 'language' => 'en',
            'local_gateways' => ['PayMongo', 'Xendit PH', 'GCash', 'Maya'], 'compliance' => ['DPA 2012'],
        ],
        'vietnam' => [
            'display' => 'Vietnam', 'currency' => 'VND', 'tax' => 'VAT 10%', 'language' => 'vi',
            'local_gateways' => ['VNPay', 'MoMo', 'ZaloPay', 'VietQR'], 'compliance' => ['Decree 13'],
        ],
        'thailand' => [
            'display' => 'Thailand', 'currency' => 'THB', 'tax' => 'VAT 7%', 'language' => 'th',
            'local_gateways' => ['Omise', '2C2P', 'PromptPay'], 'compliance' => ['PDPA Thailand'],
        ],
        'india' => [
            'display' => 'India', 'currency' => 'INR', 'tax' => 'GST 18%', 'language' => 'en',
            'local_gateways' => ['Razorpay', 'PayU India', 'Instamojo', 'UPI'], 'compliance' => ['DPDP Act'],
        ],
        'australia' => [
            'display' => 'Australia', 'currency' => 'AUD', 'tax' => 'GST 10%', 'language' => 'en',
            'local_gateways' => ['Stripe AU', 'eWAY', 'Pin Payments'], 'compliance' => ['Privacy Act 1988'],
        ],
    ],

    'features' => [
        'recurring-invoice-software' => ['display' => 'Recurring Invoice Software', 'pain' => 'Manual monthly invoicing wastes hours', 'solution' => 'Set once, auto-generate every cycle'],
        'client-portal-software' => ['display' => 'Client Portal Software', 'pain' => 'Clients keep emailing "where is my invoice?"', 'solution' => 'Self-service portal — view, pay, submit tickets'],
        'helpdesk-for-agencies' => ['display' => 'Helpdesk for Agencies', 'pain' => 'Support chaos via email + WhatsApp', 'solution' => 'Centralized tickets with SLA'],
        'self-hosted-crm' => ['display' => 'Self-Hosted CRM', 'pain' => 'SaaS lock-in, data sovereignty concerns', 'solution' => 'Deploy on your own server, own your data'],
        'open-source-crm-alternative' => ['display' => 'Open-Source CRM Alternative', 'pain' => 'Closed-source CRMs are black boxes', 'solution' => 'Modern open codebase you can audit and extend'],
        'kanban' => ['display' => 'Kanban Board', 'pain' => 'List view buries priorities', 'solution' => 'Drag-drop kanban for leads & tasks'],
        'gantt' => ['display' => 'Gantt Chart', 'pain' => 'Hard to visualize project timelines', 'solution' => 'Built-in Gantt with dependencies'],
        'time-tracking' => ['display' => 'Time Tracking', 'pain' => 'Forgetting to log hours = lost revenue', 'solution' => 'Start/stop timer per task, auto-invoice'],
        'proposals' => ['display' => 'Proposal Software', 'pain' => 'Word docs feel unprofessional', 'solution' => 'Branded proposals with e-sign'],
        'multi-currency' => ['display' => 'Multi-Currency Invoicing', 'pain' => 'Manual FX conversion errors', 'solution' => 'Each invoice in its own currency forever'],
        'email-integration' => ['display' => 'Email Integration', 'pain' => 'Context switching between Gmail and CRM', 'solution' => 'Send/receive email from inside CRM'],
        'sms-notification' => ['display' => 'SMS Notification', 'pain' => 'Missed payment reminders by email only', 'solution' => 'SMS gateway for urgent alerts'],
        'payment-gateway' => ['display' => 'Payment Gateway Integration', 'pain' => 'Manual payment reconciliation is tedious', 'solution' => 'Format-based adapter: Midtrans, Xendit, Stripe, etc'],
        'custom-fields' => ['display' => 'Custom Fields', 'pain' => 'Rigid data model can\'t fit your business', 'solution' => 'Add any field type to any module'],
        'api-access' => ['display' => 'API Access', 'pain' => 'Data silo that can\'t talk to other tools', 'solution' => 'REST API (Sanctum) for Flutter, Zapier, custom apps'],
        'webhook' => ['display' => 'Webhook System', 'pain' => 'Can\'t trigger external automation on events', 'solution' => 'Push events to your URL when invoices, leads change'],
        'lead-scoring' => ['display' => 'Lead Scoring', 'pain' => 'Sales team wastes time on cold leads', 'solution' => 'Auto-score based on behavior + manual rating'],
        'email-tracking' => ['display' => 'Email Tracking', 'pain' => 'Sent email but no idea if read', 'solution' => 'Open + click tracking per recipient'],
        'pipeline-management' => ['display' => 'Pipeline Management', 'pain' => 'Leads get forgotten in spreadsheets', 'solution' => 'Visual drag-drop pipeline phases'],
        'contact-management' => ['display' => 'Contact Management', 'pain' => 'Scattered contacts across email, phone, WhatsApp', 'solution' => 'Unified contact timeline + notes'],
        'document-management' => ['display' => 'Document Management', 'pain' => 'Proposals scattered in Google Drive', 'solution' => 'Built-in doc storage + e-sign'],
        'contract-management' => ['display' => 'Contract Management', 'pain' => 'Renewal dates get missed', 'solution' => 'Contract lifecycle + auto-renewal reminders'],
        'expense-tracking' => ['display' => 'Expense Tracking', 'pain' => 'Project costs hidden until month-end', 'solution' => 'Real-time expense logging + receipt upload'],
        'project-budget' => ['display' => 'Project Budget', 'pain' => 'Scope creep eats margin silently', 'solution' => 'Budget vs actual with alerts at thresholds'],
        'resource-planning' => ['display' => 'Resource Planning', 'pain' => 'Who is overloaded? Who is idle?', 'solution' => 'Visual workload calendar per team member'],
        'task-dependencies' => ['display' => 'Task Dependencies', 'pain' => 'Blocked tasks stall without visibility', 'solution' => 'Gantt with dependency arrows + auto-reschedule'],
        'milestone-billing' => ['display' => 'Milestone Billing', 'pain' => 'Large projects have cashflow gaps', 'solution' => 'Invoice at milestone completion automatically'],
        'retainer-billing' => ['display' => 'Retainer Billing', 'pain' => 'Monthly retainer tracking is manual', 'solution' => 'Auto-invoice retainer + overage calculation'],
        'subscription-management' => ['display' => 'Subscription Management', 'pain' => 'SaaS billing without proper tools', 'solution' => 'Recurring subscription tiers + upgrade/downgrade'],
        'auto-invoicing' => ['display' => 'Auto Invoicing', 'pain' => 'Forgetting to send invoices hurts cashflow', 'solution' => 'Invoice auto-created on project completion or schedule'],
        'late-fee-automation' => ['display' => 'Late Fee Automation', 'pain' => 'Chasing late payers manually', 'solution' => 'Auto-add late fee + reminder sequence'],
        'tax-calculation' => ['display' => 'Tax Calculation', 'pain' => 'PPN, GST, VAT errors cause audit risk', 'solution' => 'Multi-tax per invoice with region-aware defaults'],
        'financial-reporting' => ['display' => 'Financial Reporting', 'pain' => 'No visibility into business health', 'solution' => 'P&L, AR aging, cashflow dashboards'],
        'profit-loss' => ['display' => 'Profit & Loss', 'pain' => 'Unknown real profit per project', 'solution' => 'Revenue minus tracked time × rate = real margin'],
        'balance-sheet' => ['display' => 'Balance Sheet', 'pain' => 'No snapshot of assets vs liabilities', 'solution' => 'Real-time balance from all transactions'],
        'cashflow' => ['display' => 'Cashflow Management', 'pain' => 'Run out of cash without warning', 'solution' => 'Forecast runway from recurring + pipeline'],
        'sales-forecasting' => ['display' => 'Sales Forecasting', 'pain' => 'Can\'t predict next quarter revenue', 'solution' => 'Weighted pipeline → forecast with confidence'],
        'team-collaboration' => ['display' => 'Team Collaboration', 'pain' => 'Siloed work across departments', 'solution' => 'Shared workspace + @mentions + activity feed'],
        'file-sharing' => ['display' => 'File Sharing', 'pain' => 'Files attached to emails get lost', 'solution' => 'Per-client file repository with version history'],
        'activity-log' => ['display' => 'Activity Log', 'pain' => 'Who changed what and when?', 'solution' => 'Full audit trail on every record'],
        'audit-trail' => ['display' => 'Audit Trail', 'pain' => 'Can\'t prove compliance to auditors', 'solution' => 'Immutable log of all actions with IP + timestamp'],
        'two-factor-auth' => ['display' => 'Two-Factor Authentication', 'pain' => 'Password-only security is insufficient', 'solution' => 'TOTP 2FA for admin + staff accounts'],
        'role-permission' => ['display' => 'Role & Permission', 'pain' => 'Everyone sees everything — data leak risk', 'solution' => 'Granular per-module permissions + role templates'],
        'ip-whitelist' => ['display' => 'IP Whitelist', 'pain' => 'Account compromise from unknown location', 'solution' => 'Restrict admin login to office IP range'],
        'sso-integration' => ['display' => 'SSO Integration', 'pain' => 'Too many passwords across tools', 'solution' => 'Login with Google Workspace / Microsoft 365'],
        'mobile-app' => ['display' => 'Mobile App', 'pain' => 'Can\'t work from phone', 'solution' => 'Flutter mobile app with offline mode (roadmap)'],
        'offline-mode' => ['display' => 'Offline Mode', 'pain' => 'No internet = no CRM access', 'solution' => 'Queue changes offline, sync when connected'],
        'calendar-sync' => ['display' => 'Calendar Sync', 'pain' => 'Double-booking across Google/Outlook', 'solution' => 'Two-way sync tasks/events with external calendar'],
        'google-workspace' => ['display' => 'Google Workspace Integration', 'pain' => 'Duplicate data between CRM and Google', 'solution' => 'Sync contacts, calendar, and email with Google'],
        'microsoft-365' => ['display' => 'Microsoft 365 Integration', 'pain' => 'Duplicate data between CRM and Office', 'solution' => 'Sync contacts, calendar, and email with Outlook'],
    ],
];
